name: Pyre

on:
  workflow_dispatch:

permissions:
    contents: read

jobs:
  pyre:
    permissions:
      actions: read
      contents: read
      security-events: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Run Pyre
        uses: facebook/pyre-action@v0.0.1
        with:
          repo-directory: './'
          requirements-path: 'requirements.txt'
